SCREEN 12
x = 300
y = 250
A = 300
B = 250
C = 300
D = 250
E = 300
F = 250
g = 300
h = 250
i = 300
j = 250
k = 300
l = 250
m = 300
n = 250
o = 300
p = 250
q = 300
r = 250
s = 300
t = 250
u = 300
v = 250
w = 300
z = 250
a1 = 300
b1 = 250
c1 = 300
d1 = 250
e1 = 300
f1 = 250
g1 = 300
h1 = 250
i1 = 300
j1 = 250
k1 = 300
l1 = 250
m1 = 300
n1 = 250
o1 = 300
p1 = 250
q1 = 300
r1 = 250
s1 = 300
t1 = 250
u1 = 300
v1 = 250
PRINT "how big?"
INPUT big
FOR times = 1 TO big
PSET (x, y), INT(RND * 15) + 1
PSET (a1, b1), INT(RND * 15) + 1
PSET (c1, d1), INT(RND * 15) + 1
PSET (e1, f1), INT(RND * 15) + 1
PSET (g, h), INT(RND * 15) + 1
PSET (i, j), INT(RND * 15) + 1
PSET (k, l), INT(RND * 15) + 1
PSET (m, n), INT(RND * 15) + 1
PSET (o, p), INT(RND * 15) + 1
PSET (q, r), INT(RND * 15) + 1
PSET (s, t), INT(RND * 15) + 1
PSET (u, v), INT(RND * 15) + 1
PSET (w, z), INT(RND * 15) + 1
PSET (A, B), INT(RND * 15) + 1
PSET (C, D), INT(RND * 15) + 1
PSET (E, F), INT(RND * 15) + 1
PSET (g1, h1), INT(RND * 15) + 1
PSET (i1, j1), INT(RND * 15) + 1
PSET (k1, l1), INT(RND * 15) + 1
PSET (m1, n1), INT(RND * 15) + 1
PSET (o1, p1), INT(RND * 15) + 1
PSET (q1, r1), INT(RND * 15) + 1
PSET (s1, t1), INT(RND * 15) + 1
PSET (u1, v1), INT(RND * 15) + 1
x = x + 1
y = y + 1
a1 = a1 - 1
b1 = b1 - 1
c1 = c1 + 1
d1 = d1 - 1
e1 = e1 - 1
f1 = f1 + 1
g = g + 1
h = h + 0
i = i + 0
j = j + 1
k = k - 1
l = l - 0
m = m - 0
n = n - 1
o = o + 1
p = p + .5
q = q + .5
r = r + 1
s = s - 1
t = t - .5
u = u - .5
v = v - 1
w = w - 1.5
z = z - 1
A = A - 1
B = B - 1.5
C = C + 1.5
D = D + 1
E = E + 1
F = F + 1.5
g1 = g1 + 1
h1 = h1 - .5
i1 = i1 - .5
j1 = j1 + 1
k1 = k1 - 1
l1 = l1 + .5
m1 = m1 + .5
n1 = n1 - 1
o1 = o1 + 1
p1 = p1 - 1.5
q1 = q1 - 1.5
r1 = r1 + 1
s1 = s1 - 1
t1 = t1 + 1.5
u1 = u1 + 1.5
v1 = v1 - 1
FOR waste = 1 TO 1000
NEXT waste
NEXT times

